# -*- coding: utf-8 -*-
"""
여행 영어 회화 스크립트 모음 (초보자용 / A2-B1 수준)

매일 텔레그램으로 한 개씩 순환하며 전송됩니다.
새 시나리오를 추가하고 싶으면 아래 SCENARIOS 리스트에 같은 형식으로 넣으면 됩니다.

각 항목 형식:
{
    "emoji": "이모지",
    "title_en": "영어 제목",
    "title_ko": "한국어 제목",
    "dialogue": [
        {"speaker": "상대 역할", "en": "영어 대사", "ko": "한국어 뜻"},
        ...
    ],
    "key_phrases": [
        {"en": "핵심 표현", "ko": "뜻 / 사용 상황"},
        ...
    ],
    "tip": "오늘의 팁 한 줄",
}
"""

SCENARIOS = [
    {
        "emoji": "✈️",
        "title_en": "Airport Check-in",
        "title_ko": "공항 체크인",
        "dialogue": [
            {"speaker": "Agent", "en": "Good morning. May I see your passport, please?", "ko": "안녕하세요. 여권 좀 보여주시겠어요?"},
            {"speaker": "You", "en": "Sure, here you go.", "ko": "네, 여기 있습니다."},
            {"speaker": "Agent", "en": "Where are you flying to today?", "ko": "오늘 어디로 가시나요?"},
            {"speaker": "You", "en": "I'm flying to London.", "ko": "런던으로 갑니다."},
            {"speaker": "Agent", "en": "Do you have any bags to check?", "ko": "부칠 짐이 있으신가요?"},
            {"speaker": "You", "en": "Yes, just one suitcase.", "ko": "네, 캐리어 하나요."},
            {"speaker": "Agent", "en": "Here's your boarding pass. The gate is 23.", "ko": "탑승권 여기 있습니다. 게이트는 23번이에요."},
        ],
        "key_phrases": [
            {"en": "Here you go.", "ko": "여기 있어요 (물건을 건넬 때)"},
            {"en": "I'm flying to ___.", "ko": "저는 ___로 가요"},
            {"en": "a bag to check", "ko": "부칠 짐 (수하물)"},
            {"en": "boarding pass", "ko": "탑승권"},
        ],
        "tip": "여권/표를 건넬 땐 'Here you go.' 한마디면 충분해요.",
    },
    {
        "emoji": "🛂",
        "title_en": "Airport Security",
        "title_ko": "공항 보안검색",
        "dialogue": [
            {"speaker": "Officer", "en": "Please put your bag on the belt.", "ko": "가방을 벨트 위에 올려주세요."},
            {"speaker": "Officer", "en": "Take off your jacket and shoes, please.", "ko": "재킷과 신발을 벗어주세요."},
            {"speaker": "You", "en": "Should I take out my laptop?", "ko": "노트북을 꺼내야 하나요?"},
            {"speaker": "Officer", "en": "Yes, put it in a separate tray.", "ko": "네, 별도 바구니에 넣어주세요."},
            {"speaker": "Officer", "en": "Okay, you're good. Have a nice flight.", "ko": "됐습니다. 좋은 비행 되세요."},
            {"speaker": "You", "en": "Thank you!", "ko": "감사합니다!"},
        ],
        "key_phrases": [
            {"en": "take off ___", "ko": "___을 벗다"},
            {"en": "take out ___", "ko": "___을 꺼내다"},
            {"en": "Should I ___?", "ko": "제가 ___해야 하나요? (확인 질문)"},
            {"en": "You're good.", "ko": "다 됐어요 / 통과예요"},
        ],
        "tip": "'Should I ~?'는 뭘 해야 할지 정중히 물어볼 때 아주 유용해요.",
    },
    {
        "emoji": "🛫",
        "title_en": "On the Plane",
        "title_ko": "기내에서",
        "dialogue": [
            {"speaker": "You", "en": "Excuse me, I think this is my seat.", "ko": "실례합니다, 여기가 제 자리인 것 같아요."},
            {"speaker": "Passenger", "en": "Oh, sorry. Let me move.", "ko": "아, 죄송해요. 비켜드릴게요."},
            {"speaker": "Crew", "en": "Would you like chicken or beef?", "ko": "닭고기와 소고기 중 어떤 걸 드릴까요?"},
            {"speaker": "You", "en": "Chicken, please. And some water.", "ko": "닭고기로 주세요. 그리고 물도요."},
            {"speaker": "You", "en": "Could I get a blanket, please?", "ko": "담요 하나 주실 수 있나요?"},
            {"speaker": "Crew", "en": "Of course. Here you are.", "ko": "물론이죠. 여기 있습니다."},
        ],
        "key_phrases": [
            {"en": "I think this is my seat.", "ko": "여기 제 자리인 것 같아요"},
            {"en": "Would you like A or B?", "ko": "A와 B 중 무엇으로 하시겠어요?"},
            {"en": "Could I get ___, please?", "ko": "___ 좀 주실 수 있나요? (정중한 요청)"},
            {"en": "Here you are.", "ko": "여기 있어요"},
        ],
        "tip": "'Could I get ~, please?'는 기내·식당·카페에서 두루 쓰는 만능 요청 표현이에요.",
    },
    {
        "emoji": "🛃",
        "title_en": "Immigration",
        "title_ko": "입국 심사",
        "dialogue": [
            {"speaker": "Officer", "en": "What's the purpose of your visit?", "ko": "방문 목적이 무엇인가요?"},
            {"speaker": "You", "en": "I'm here on vacation.", "ko": "휴가차 왔습니다."},
            {"speaker": "Officer", "en": "How long will you stay?", "ko": "얼마나 머무르실 건가요?"},
            {"speaker": "You", "en": "For one week.", "ko": "일주일이요."},
            {"speaker": "Officer", "en": "Where are you staying?", "ko": "어디에 묵으세요?"},
            {"speaker": "You", "en": "At a hotel downtown.", "ko": "시내에 있는 호텔에요."},
            {"speaker": "Officer", "en": "Enjoy your trip.", "ko": "즐거운 여행 되세요."},
        ],
        "key_phrases": [
            {"en": "the purpose of your visit", "ko": "방문 목적"},
            {"en": "I'm here on vacation.", "ko": "휴가로 왔어요"},
            {"en": "for one week", "ko": "일주일 동안"},
            {"en": "downtown", "ko": "시내, 도심"},
        ],
        "tip": "입국 심사는 짧고 분명하게! 'On vacation.', 'One week.'처럼 답해도 괜찮아요.",
    },
    {
        "emoji": "🧳",
        "title_en": "Baggage Claim & Lost Luggage",
        "title_ko": "수하물 찾기 & 분실",
        "dialogue": [
            {"speaker": "You", "en": "Excuse me, my suitcase didn't come out.", "ko": "실례합니다, 제 캐리어가 안 나왔어요."},
            {"speaker": "Staff", "en": "Can I see your baggage tag?", "ko": "수하물 표를 보여주시겠어요?"},
            {"speaker": "You", "en": "Here it is. What should I do now?", "ko": "여기 있어요. 이제 어떻게 해야 하나요?"},
            {"speaker": "Staff", "en": "Please fill out this form with your address.", "ko": "이 양식에 주소를 적어주세요."},
            {"speaker": "You", "en": "When will I get my bag?", "ko": "제 가방은 언제 받을 수 있나요?"},
            {"speaker": "Staff", "en": "We'll deliver it to your hotel tomorrow.", "ko": "내일 호텔로 배송해 드릴게요."},
        ],
        "key_phrases": [
            {"en": "My ___ didn't come out.", "ko": "제 ___이 안 나왔어요"},
            {"en": "baggage tag", "ko": "수하물 표(태그)"},
            {"en": "fill out this form", "ko": "이 양식을 작성하다"},
            {"en": "When will I get ___?", "ko": "___을 언제 받을 수 있나요?"},
        ],
        "tip": "문제가 생기면 'What should I do now?'로 다음 행동을 물어보세요.",
    },
    {
        "emoji": "🚕",
        "title_en": "Taking a Taxi",
        "title_ko": "택시 타기",
        "dialogue": [
            {"speaker": "You", "en": "Hi, could you take me to this address?", "ko": "안녕하세요, 이 주소로 가주실 수 있나요?"},
            {"speaker": "Driver", "en": "Sure. Hop in.", "ko": "그럼요. 타세요."},
            {"speaker": "You", "en": "How long will it take?", "ko": "얼마나 걸릴까요?"},
            {"speaker": "Driver", "en": "About 20 minutes.", "ko": "20분 정도요."},
            {"speaker": "You", "en": "How much is it?", "ko": "얼마예요?"},
            {"speaker": "Driver", "en": "That'll be 15 dollars.", "ko": "15달러입니다."},
            {"speaker": "You", "en": "Keep the change.", "ko": "잔돈은 가지세요."},
        ],
        "key_phrases": [
            {"en": "Could you take me to ___?", "ko": "___로 데려다 주실 수 있나요?"},
            {"en": "How long will it take?", "ko": "얼마나 걸려요?"},
            {"en": "How much is it?", "ko": "얼마예요?"},
            {"en": "Keep the change.", "ko": "잔돈은 가지세요 (팁)"},
        ],
        "tip": "주소를 보여주며 'this address'라고 하면 발음 걱정 없이 통해요.",
    },
    {
        "emoji": "🏨",
        "title_en": "Hotel Check-in",
        "title_ko": "호텔 체크인",
        "dialogue": [
            {"speaker": "You", "en": "Hi, I have a reservation under Kim.", "ko": "안녕하세요, Kim으로 예약했어요."},
            {"speaker": "Clerk", "en": "Let me check. Yes, two nights, right?", "ko": "확인해 볼게요. 네, 2박 맞으시죠?"},
            {"speaker": "You", "en": "That's right.", "ko": "맞아요."},
            {"speaker": "Clerk", "en": "May I have your passport and a card?", "ko": "여권과 카드를 주시겠어요?"},
            {"speaker": "You", "en": "Here you go. What time is breakfast?", "ko": "여기요. 조식은 몇 시예요?"},
            {"speaker": "Clerk", "en": "From 7 to 10. Your room is on the 5th floor.", "ko": "7시부터 10시까지요. 방은 5층입니다."},
        ],
        "key_phrases": [
            {"en": "I have a reservation under ___.", "ko": "___ 이름으로 예약했어요"},
            {"en": "two nights", "ko": "2박"},
            {"en": "What time is breakfast?", "ko": "조식은 몇 시예요?"},
            {"en": "on the 5th floor", "ko": "5층에"},
        ],
        "tip": "예약 확인은 'under + 이름'! 'a reservation under Kim'처럼 말하면 돼요.",
    },
    {
        "emoji": "🛎️",
        "title_en": "Hotel Front Desk Requests",
        "title_ko": "호텔 요청하기",
        "dialogue": [
            {"speaker": "You", "en": "Hi, the Wi-Fi isn't working in my room.", "ko": "안녕하세요, 방에 와이파이가 안 돼요."},
            {"speaker": "Clerk", "en": "I'm sorry. I'll send someone up.", "ko": "죄송합니다. 직원을 올려보낼게요."},
            {"speaker": "You", "en": "Also, could I get two more towels?", "ko": "그리고 수건 두 장 더 받을 수 있을까요?"},
            {"speaker": "Clerk", "en": "Of course. Anything else?", "ko": "물론이죠. 더 필요하신 거 있으세요?"},
            {"speaker": "You", "en": "Can I have a wake-up call at 7?", "ko": "7시에 모닝콜 받을 수 있을까요?"},
            {"speaker": "Clerk", "en": "Sure, I'll set it up.", "ko": "네, 설정해 드릴게요."},
        ],
        "key_phrases": [
            {"en": "___ isn't working.", "ko": "___이 작동이 안 돼요 / 고장났어요"},
            {"en": "Could I get ___?", "ko": "___을 받을 수 있을까요?"},
            {"en": "Anything else?", "ko": "더 필요한 거 있으세요?"},
            {"en": "a wake-up call", "ko": "모닝콜"},
        ],
        "tip": "고장 났을 때 'It isn't working.' 한마디면 충분히 통해요.",
    },
    {
        "emoji": "🍽️",
        "title_en": "Getting a Table",
        "title_ko": "식당 자리 잡기",
        "dialogue": [
            {"speaker": "Host", "en": "Hi, how many people?", "ko": "안녕하세요, 몇 분이세요?"},
            {"speaker": "You", "en": "A table for two, please.", "ko": "두 명 자리 부탁해요."},
            {"speaker": "Host", "en": "Do you have a reservation?", "ko": "예약하셨나요?"},
            {"speaker": "You", "en": "No, we don't.", "ko": "아니요, 안 했어요."},
            {"speaker": "Host", "en": "No problem. It'll be a 10-minute wait.", "ko": "괜찮아요. 10분 정도 기다리셔야 해요."},
            {"speaker": "You", "en": "That's fine, thanks.", "ko": "괜찮아요, 감사합니다."},
        ],
        "key_phrases": [
            {"en": "A table for two, please.", "ko": "두 명 자리 주세요"},
            {"en": "Do you have a reservation?", "ko": "예약하셨어요?"},
            {"en": "a 10-minute wait", "ko": "10분 대기"},
            {"en": "That's fine.", "ko": "괜찮아요"},
        ],
        "tip": "인원 수는 'A table for + 숫자'로! 'a table for two' = 2인석.",
    },
    {
        "emoji": "🍝",
        "title_en": "Ordering Food",
        "title_ko": "음식 주문하기",
        "dialogue": [
            {"speaker": "Server", "en": "Are you ready to order?", "ko": "주문하시겠어요?"},
            {"speaker": "You", "en": "Yes. What do you recommend?", "ko": "네. 뭘 추천하세요?"},
            {"speaker": "Server", "en": "The grilled salmon is very popular.", "ko": "구운 연어가 아주 인기 있어요."},
            {"speaker": "You", "en": "Sounds good. I'll have that.", "ko": "좋네요. 그걸로 할게요."},
            {"speaker": "Server", "en": "Anything to drink?", "ko": "마실 것은요?"},
            {"speaker": "You", "en": "Just water, please.", "ko": "그냥 물이요."},
        ],
        "key_phrases": [
            {"en": "What do you recommend?", "ko": "뭘 추천하세요?"},
            {"en": "I'll have ___.", "ko": "___로 할게요 (주문)"},
            {"en": "Sounds good.", "ko": "좋네요 / 괜찮네요"},
            {"en": "Just water, please.", "ko": "물만 주세요"},
        ],
        "tip": "메뉴 고민될 땐 'What do you recommend?' 추천을 물어보세요.",
    },
    {
        "emoji": "💳",
        "title_en": "Paying the Bill",
        "title_ko": "계산하기",
        "dialogue": [
            {"speaker": "You", "en": "Could we get the check, please?", "ko": "계산서 좀 주시겠어요?"},
            {"speaker": "Server", "en": "Sure. Here you go.", "ko": "네. 여기 있습니다."},
            {"speaker": "You", "en": "Can I pay by card?", "ko": "카드로 계산해도 되나요?"},
            {"speaker": "Server", "en": "Of course.", "ko": "물론이죠."},
            {"speaker": "You", "en": "Can we split the bill?", "ko": "나눠서 계산할 수 있나요?"},
            {"speaker": "Server", "en": "No problem. How would you like to split it?", "ko": "괜찮아요. 어떻게 나눠 드릴까요?"},
        ],
        "key_phrases": [
            {"en": "Could we get the check, please?", "ko": "계산서 주시겠어요?"},
            {"en": "Can I pay by card?", "ko": "카드로 계산되나요?"},
            {"en": "split the bill", "ko": "각자 / 나눠서 계산하다"},
            {"en": "the check / the bill", "ko": "계산서"},
        ],
        "tip": "미국은 'check', 영국은 'bill'을 더 자주 써요. 둘 다 통합니다.",
    },
    {
        "emoji": "☕",
        "title_en": "At a Coffee Shop",
        "title_ko": "커피숍에서",
        "dialogue": [
            {"speaker": "Barista", "en": "Hi, what can I get for you?", "ko": "안녕하세요, 뭐 드릴까요?"},
            {"speaker": "You", "en": "A medium latte, please.", "ko": "라떼 미디엄 사이즈로 주세요."},
            {"speaker": "Barista", "en": "For here or to go?", "ko": "여기서 드세요, 가져가세요?"},
            {"speaker": "You", "en": "To go, please.", "ko": "가져갈게요."},
            {"speaker": "Barista", "en": "Can I have a name for the order?", "ko": "주문하신 분 성함이 어떻게 되세요?"},
            {"speaker": "You", "en": "It's Jin.", "ko": "Jin이에요."},
        ],
        "key_phrases": [
            {"en": "What can I get for you?", "ko": "뭐 드릴까요?"},
            {"en": "For here or to go?", "ko": "매장에서 드세요, 포장이세요?"},
            {"en": "to go", "ko": "포장, 테이크아웃"},
            {"en": "a name for the order", "ko": "주문자 이름"},
        ],
        "tip": "'테이크아웃'은 영어로 'to go'! 'For here'는 매장 식사예요.",
    },
    {
        "emoji": "🗺️",
        "title_en": "Asking for Directions",
        "title_ko": "길 물어보기",
        "dialogue": [
            {"speaker": "You", "en": "Excuse me, how do I get to the station?", "ko": "실례합니다, 역에 어떻게 가나요?"},
            {"speaker": "Local", "en": "Go straight and turn left at the corner.", "ko": "쭉 가다가 모퉁이에서 왼쪽으로 도세요."},
            {"speaker": "You", "en": "Is it far?", "ko": "먼가요?"},
            {"speaker": "Local", "en": "No, about a five-minute walk.", "ko": "아니요, 걸어서 5분 정도예요."},
            {"speaker": "You", "en": "Thank you so much!", "ko": "정말 감사합니다!"},
            {"speaker": "Local", "en": "No problem. Have a good day.", "ko": "천만에요. 좋은 하루 되세요."},
        ],
        "key_phrases": [
            {"en": "How do I get to ___?", "ko": "___에 어떻게 가나요?"},
            {"en": "Go straight.", "ko": "쭉 가세요"},
            {"en": "turn left / right", "ko": "왼쪽/오른쪽으로 돌다"},
            {"en": "Is it far?", "ko": "먼가요?"},
        ],
        "tip": "길 찾기 만능 질문 = 'How do I get to ___?' 장소만 바꿔 쓰세요.",
    },
    {
        "emoji": "🚇",
        "title_en": "Public Transport",
        "title_ko": "대중교통 이용",
        "dialogue": [
            {"speaker": "You", "en": "Which line goes to the airport?", "ko": "공항 가려면 몇 호선 타나요?"},
            {"speaker": "Staff", "en": "Take the blue line and transfer at Central.", "ko": "파란색 노선을 타고 Central에서 갈아타세요."},
            {"speaker": "You", "en": "How many stops is it?", "ko": "몇 정거장이에요?"},
            {"speaker": "Staff", "en": "About six stops.", "ko": "6정거장 정도요."},
            {"speaker": "You", "en": "Where can I buy a ticket?", "ko": "표는 어디서 사나요?"},
            {"speaker": "Staff", "en": "At the machine over there.", "ko": "저쪽 기계에서요."},
        ],
        "key_phrases": [
            {"en": "Which line goes to ___?", "ko": "___ 가려면 몇 호선이에요?"},
            {"en": "transfer at ___", "ko": "___에서 환승하다"},
            {"en": "How many stops?", "ko": "몇 정거장이에요?"},
            {"en": "Where can I buy a ticket?", "ko": "표는 어디서 사나요?"},
        ],
        "tip": "'transfer'는 '갈아타다'. 'transfer at + 역 이름'으로 기억하세요.",
    },
    {
        "emoji": "👕",
        "title_en": "Shopping for Clothes",
        "title_ko": "옷 쇼핑하기",
        "dialogue": [
            {"speaker": "Clerk", "en": "Hi, are you looking for anything?", "ko": "안녕하세요, 찾으시는 거 있으세요?"},
            {"speaker": "You", "en": "I'm just looking, thanks.", "ko": "그냥 구경하는 거예요, 감사합니다."},
            {"speaker": "You", "en": "Actually, can I try this on?", "ko": "아, 이거 입어봐도 될까요?"},
            {"speaker": "Clerk", "en": "Sure. The fitting room is over there.", "ko": "네. 탈의실은 저쪽이에요."},
            {"speaker": "You", "en": "Do you have this in a smaller size?", "ko": "이거 더 작은 사이즈 있나요?"},
            {"speaker": "Clerk", "en": "Let me check for you.", "ko": "확인해 드릴게요."},
        ],
        "key_phrases": [
            {"en": "I'm just looking.", "ko": "그냥 구경하는 거예요"},
            {"en": "Can I try this on?", "ko": "이거 입어봐도 되나요?"},
            {"en": "Do you have this in a ___ size?", "ko": "이거 ___ 사이즈 있나요?"},
            {"en": "fitting room", "ko": "탈의실"},
        ],
        "tip": "점원이 다가오면 부담 없이 'I'm just looking.'이라고 하면 돼요.",
    },
    {
        "emoji": "🏷️",
        "title_en": "Asking the Price",
        "title_ko": "가격 묻기 & 흥정",
        "dialogue": [
            {"speaker": "You", "en": "How much is this?", "ko": "이거 얼마예요?"},
            {"speaker": "Seller", "en": "It's 40 dollars.", "ko": "40달러예요."},
            {"speaker": "You", "en": "That's a bit expensive. Can you give me a discount?", "ko": "좀 비싸네요. 할인해 주실 수 있나요?"},
            {"speaker": "Seller", "en": "I can do 35.", "ko": "35달러까지 해드릴게요."},
            {"speaker": "You", "en": "Okay, I'll take it.", "ko": "좋아요, 그걸로 할게요."},
            {"speaker": "Seller", "en": "Great choice!", "ko": "탁월한 선택이세요!"},
        ],
        "key_phrases": [
            {"en": "How much is this?", "ko": "이거 얼마예요?"},
            {"en": "That's a bit expensive.", "ko": "좀 비싸네요"},
            {"en": "Can you give me a discount?", "ko": "할인해 주실 수 있나요?"},
            {"en": "I'll take it.", "ko": "이걸로 할게요 / 살게요"},
        ],
        "tip": "살 마음을 정하면 'I'll take it.' 한마디로 결제 의사를 표현해요.",
    },
    {
        "emoji": "🛒",
        "title_en": "Convenience Store",
        "title_ko": "편의점 / 마트",
        "dialogue": [
            {"speaker": "You", "en": "Excuse me, where's the water?", "ko": "실례합니다, 물은 어디 있나요?"},
            {"speaker": "Clerk", "en": "Aisle 3, on your right.", "ko": "3번 통로, 오른쪽에 있어요."},
            {"speaker": "Clerk", "en": "Would you like a bag?", "ko": "봉투 드릴까요?"},
            {"speaker": "You", "en": "Yes, please. How much is the bag?", "ko": "네, 주세요. 봉투 얼마예요?"},
            {"speaker": "Clerk", "en": "Ten cents. Anything else?", "ko": "10센트요. 더 필요한 거 있으세요?"},
            {"speaker": "You", "en": "No, that's all. Thanks.", "ko": "아니요, 그게 다예요. 감사합니다."},
        ],
        "key_phrases": [
            {"en": "Where's the ___?", "ko": "___은 어디 있어요?"},
            {"en": "aisle", "ko": "(마트) 통로, 진열대 열"},
            {"en": "Would you like a bag?", "ko": "봉투 드릴까요?"},
            {"en": "That's all.", "ko": "그게 다예요 (주문 끝)"},
        ],
        "tip": "물건 위치는 'Where's the ___?'로! 계산 끝낼 땐 'That's all.'",
    },
    {
        "emoji": "💊",
        "title_en": "At the Pharmacy",
        "title_ko": "약국에서",
        "dialogue": [
            {"speaker": "You", "en": "Hi, do you have anything for a headache?", "ko": "안녕하세요, 두통약 있나요?"},
            {"speaker": "Pharmacist", "en": "Sure. How long have you had it?", "ko": "네. 얼마나 됐어요?"},
            {"speaker": "You", "en": "Since this morning.", "ko": "오늘 아침부터요."},
            {"speaker": "Pharmacist", "en": "Take one of these after meals.", "ko": "식후에 이거 한 알 드세요."},
            {"speaker": "You", "en": "How many times a day?", "ko": "하루에 몇 번이요?"},
            {"speaker": "Pharmacist", "en": "Three times a day.", "ko": "하루 세 번이요."},
        ],
        "key_phrases": [
            {"en": "Do you have anything for ___?", "ko": "___에 듣는 약 있나요?"},
            {"en": "after meals", "ko": "식후에"},
            {"en": "How many times a day?", "ko": "하루에 몇 번이요?"},
            {"en": "Take one.", "ko": "한 알 드세요"},
        ],
        "tip": "증상은 'something for a + 증상'! 두통=headache, 감기=cold, 복통=stomachache.",
    },
    {
        "emoji": "ℹ️",
        "title_en": "Tourist Information",
        "title_ko": "관광 안내소",
        "dialogue": [
            {"speaker": "You", "en": "Hi, what's worth seeing around here?", "ko": "안녕하세요, 이 근처에 볼 만한 게 뭐가 있나요?"},
            {"speaker": "Staff", "en": "The old town and the museum are great.", "ko": "구시가지와 박물관이 좋아요."},
            {"speaker": "You", "en": "Do you have a map?", "ko": "지도 있나요?"},
            {"speaker": "Staff", "en": "Here's a free one.", "ko": "여기 무료 지도 있어요."},
            {"speaker": "You", "en": "What time does the museum close?", "ko": "박물관은 몇 시에 닫아요?"},
            {"speaker": "Staff", "en": "At 6 p.m.", "ko": "오후 6시요."},
        ],
        "key_phrases": [
            {"en": "What's worth seeing?", "ko": "볼 만한 게 뭐예요?"},
            {"en": "Do you have a map?", "ko": "지도 있나요?"},
            {"en": "What time does it close?", "ko": "몇 시에 닫아요?"},
            {"en": "the old town", "ko": "구시가지"},
        ],
        "tip": "추천 명소는 'What's worth seeing around here?'로 물어보세요.",
    },
    {
        "emoji": "🎫",
        "title_en": "Buying Tickets",
        "title_ko": "입장권 사기",
        "dialogue": [
            {"speaker": "You", "en": "Two adult tickets, please.", "ko": "성인 두 장 주세요."},
            {"speaker": "Clerk", "en": "That's 30 dollars.", "ko": "30달러입니다."},
            {"speaker": "You", "en": "Is there a student discount?", "ko": "학생 할인 있나요?"},
            {"speaker": "Clerk", "en": "Yes, with a student ID.", "ko": "네, 학생증 있으면요."},
            {"speaker": "You", "en": "What time does the show start?", "ko": "공연은 몇 시에 시작해요?"},
            {"speaker": "Clerk", "en": "At 3 p.m. Enjoy!", "ko": "오후 3시예요. 즐거운 시간 되세요!"},
        ],
        "key_phrases": [
            {"en": "Two adult tickets, please.", "ko": "성인 두 장 주세요"},
            {"en": "Is there a ___ discount?", "ko": "___ 할인 있나요?"},
            {"en": "What time does it start?", "ko": "몇 시에 시작해요?"},
            {"en": "student ID", "ko": "학생증"},
        ],
        "tip": "표 살 땐 '인원수 + adult/child + tickets'! 예: 'one adult and one child'.",
    },
    {
        "emoji": "🆘",
        "title_en": "Asking for Help",
        "title_ko": "도움 요청하기",
        "dialogue": [
            {"speaker": "You", "en": "Excuse me, I think I'm lost.", "ko": "실례합니다, 길을 잃은 것 같아요."},
            {"speaker": "Local", "en": "Where are you trying to go?", "ko": "어디 가시려고요?"},
            {"speaker": "You", "en": "I'm looking for this hotel.", "ko": "이 호텔을 찾고 있어요."},
            {"speaker": "Local", "en": "Oh, it's just behind that building.", "ko": "아, 저 건물 바로 뒤예요."},
            {"speaker": "You", "en": "Could you show me on the map?", "ko": "지도에서 짚어주실 수 있나요?"},
            {"speaker": "Local", "en": "Sure, we're right here.", "ko": "그럼요, 우리는 지금 여기 있어요."},
        ],
        "key_phrases": [
            {"en": "I think I'm lost.", "ko": "길을 잃은 것 같아요"},
            {"en": "I'm looking for ___.", "ko": "___을 찾고 있어요"},
            {"en": "Could you show me on the map?", "ko": "지도에서 보여주실 수 있나요?"},
            {"en": "behind that building", "ko": "저 건물 뒤에"},
        ],
        "tip": "말로 설명이 어려우면 'Could you show me on the map?'가 최고예요.",
    },
    {
        "emoji": "🤒",
        "title_en": "Feeling Sick",
        "title_ko": "아플 때 / 병원",
        "dialogue": [
            {"speaker": "Doctor", "en": "What seems to be the problem?", "ko": "어디가 안 좋으세요?"},
            {"speaker": "You", "en": "I have a fever and a sore throat.", "ko": "열이 나고 목이 아파요."},
            {"speaker": "Doctor", "en": "How long have you felt this way?", "ko": "이런 지 얼마나 됐어요?"},
            {"speaker": "You", "en": "Since yesterday.", "ko": "어제부터요."},
            {"speaker": "Doctor", "en": "You have a cold. Get some rest.", "ko": "감기예요. 푹 쉬세요."},
            {"speaker": "You", "en": "Thank you, doctor.", "ko": "감사합니다, 선생님."},
        ],
        "key_phrases": [
            {"en": "I have a fever.", "ko": "열이 나요"},
            {"en": "a sore throat", "ko": "인후통, 목 아픔"},
            {"en": "What seems to be the problem?", "ko": "어디가 안 좋으세요?"},
            {"en": "Get some rest.", "ko": "푹 쉬세요"},
        ],
        "tip": "증상은 'I have a + 증상'으로! 열=fever, 기침=cough, 콧물=runny nose.",
    },
    {
        "emoji": "🧾",
        "title_en": "Hotel Check-out",
        "title_ko": "호텔 체크아웃",
        "dialogue": [
            {"speaker": "You", "en": "Hi, I'd like to check out, please.", "ko": "안녕하세요, 체크아웃하려고요."},
            {"speaker": "Clerk", "en": "Sure. How was your stay?", "ko": "네. 머무시는 동안 어떠셨어요?"},
            {"speaker": "You", "en": "It was great, thank you.", "ko": "아주 좋았어요, 감사합니다."},
            {"speaker": "Clerk", "en": "Here's your bill. Anything from the minibar?", "ko": "계산서 여기 있어요. 미니바 이용하셨어요?"},
            {"speaker": "You", "en": "No. Can I leave my bags here for a while?", "ko": "아니요. 가방 잠깐 맡길 수 있을까요?"},
            {"speaker": "Clerk", "en": "Of course, no problem.", "ko": "물론이죠, 문제없어요."},
        ],
        "key_phrases": [
            {"en": "I'd like to check out.", "ko": "체크아웃할게요"},
            {"en": "How was your stay?", "ko": "지내신 건 어떠셨어요?"},
            {"en": "Can I leave my bags here?", "ko": "짐 맡겨도 될까요?"},
            {"en": "for a while", "ko": "잠시 동안"},
        ],
        "tip": "'I'd like to ___'는 'I want to'보다 정중해요. 어디서나 쓰기 좋아요.",
    },
    {
        "emoji": "🚗",
        "title_en": "Renting a Car",
        "title_ko": "렌터카 빌리기",
        "dialogue": [
            {"speaker": "You", "en": "Hi, I'd like to rent a car for three days.", "ko": "안녕하세요, 3일간 차를 빌리고 싶어요."},
            {"speaker": "Clerk", "en": "Do you have a driver's license?", "ko": "운전면허증 있으세요?"},
            {"speaker": "You", "en": "Yes, here it is.", "ko": "네, 여기 있어요."},
            {"speaker": "Clerk", "en": "Would you like insurance?", "ko": "보험 드시겠어요?"},
            {"speaker": "You", "en": "Yes, please. Is gas included?", "ko": "네, 부탁해요. 기름값 포함인가요?"},
            {"speaker": "Clerk", "en": "No, please return it with a full tank.", "ko": "아니요, 가득 채워서 반납해 주세요."},
        ],
        "key_phrases": [
            {"en": "I'd like to rent a car for ___.", "ko": "___ 동안 차를 빌리고 싶어요"},
            {"en": "driver's license", "ko": "운전면허증"},
            {"en": "Is ___ included?", "ko": "___이 포함되어 있나요?"},
            {"en": "a full tank", "ko": "기름 가득"},
        ],
        "tip": "포함 여부 확인은 'Is ___ included?'. 기름·보험·세금 모두 이걸로 물어요.",
    },
    {
        "emoji": "💱",
        "title_en": "Currency Exchange",
        "title_ko": "환전하기",
        "dialogue": [
            {"speaker": "You", "en": "Hi, I'd like to exchange some money.", "ko": "안녕하세요, 환전하고 싶어요."},
            {"speaker": "Clerk", "en": "How much would you like to change?", "ko": "얼마나 바꾸시겠어요?"},
            {"speaker": "You", "en": "A hundred dollars, please. What's the rate today?", "ko": "100달러요. 오늘 환율은 어떻게 되나요?"},
            {"speaker": "Clerk", "en": "Here's the rate. There's a small fee.", "ko": "환율 여기 있어요. 약간의 수수료가 있어요."},
            {"speaker": "You", "en": "Okay. Could I get smaller bills?", "ko": "알겠어요. 작은 단위로 주실 수 있나요?"},
        ],
        "key_phrases": [
            {"en": "I'd like to exchange some money.", "ko": "환전하고 싶어요"},
            {"en": "exchange rate", "ko": "환율"},
            {"en": "Is there a fee?", "ko": "수수료 있나요?"},
            {"en": "smaller bills", "ko": "작은 단위 지폐"},
        ],
        "tip": "큰 지폐가 부담되면 'Could I get smaller bills?'로 잔돈을 요청하세요.",
    },
    {
        "emoji": "📱",
        "title_en": "Buying a SIM Card",
        "title_ko": "유심(SIM) 사기",
        "dialogue": [
            {"speaker": "You", "en": "Hi, I need a SIM card for my phone.", "ko": "안녕하세요, 휴대폰용 유심이 필요해요."},
            {"speaker": "Clerk", "en": "How long are you staying?", "ko": "얼마나 머무세요?"},
            {"speaker": "You", "en": "About a week.", "ko": "일주일 정도요."},
            {"speaker": "Clerk", "en": "This plan has 10GB of data.", "ko": "이 요금제는 데이터 10기가예요."},
            {"speaker": "You", "en": "Does it include calls?", "ko": "통화도 포함인가요?"},
            {"speaker": "Clerk", "en": "Yes. Let me set it up for you.", "ko": "네. 설정해 드릴게요."},
        ],
        "key_phrases": [
            {"en": "I need a SIM card.", "ko": "유심이 필요해요"},
            {"en": "data", "ko": "데이터"},
            {"en": "Does it include ___?", "ko": "___이 포함되나요?"},
            {"en": "set it up", "ko": "설정하다, 개통하다"},
        ],
        "tip": "데이터 용량은 그냥 숫자+GB로! '10GB'는 'ten gig'이라고도 말해요.",
    },
    {
        "emoji": "👋",
        "title_en": "Small Talk",
        "title_ko": "가벼운 대화 / 인사",
        "dialogue": [
            {"speaker": "Local", "en": "Hi! Where are you from?", "ko": "안녕하세요! 어디서 오셨어요?"},
            {"speaker": "You", "en": "I'm from South Korea.", "ko": "한국에서 왔어요."},
            {"speaker": "Local", "en": "Nice! Is this your first time here?", "ko": "좋네요! 여기 처음이세요?"},
            {"speaker": "You", "en": "Yes, it is. I love it so far.", "ko": "네, 맞아요. 지금까지 너무 좋아요."},
            {"speaker": "Local", "en": "How long are you here for?", "ko": "얼마나 계세요?"},
            {"speaker": "You", "en": "Just a few days.", "ko": "며칠만요."},
        ],
        "key_phrases": [
            {"en": "Where are you from?", "ko": "어디서 오셨어요?"},
            {"en": "Is this your first time here?", "ko": "여기 처음이세요?"},
            {"en": "so far", "ko": "지금까지는"},
            {"en": "How long are you here for?", "ko": "얼마나 머무세요?"},
        ],
        "tip": "여행 중 가장 자주 듣는 질문 'Where are you from?' 답을 미리 준비해 두세요.",
    },
    {
        "emoji": "🗽",
        "title_en": "Booking a Tour",
        "title_ko": "투어 예약하기",
        "dialogue": [
            {"speaker": "You", "en": "Hi, I'd like to book a city tour.", "ko": "안녕하세요, 시티 투어를 예약하고 싶어요."},
            {"speaker": "Staff", "en": "For how many people?", "ko": "몇 분이세요?"},
            {"speaker": "You", "en": "Two, for tomorrow morning.", "ko": "두 명이요, 내일 오전으로요."},
            {"speaker": "Staff", "en": "The tour starts at 9 and lasts three hours.", "ko": "투어는 9시에 시작하고 3시간 걸려요."},
            {"speaker": "You", "en": "Where do we meet?", "ko": "어디서 만나나요?"},
            {"speaker": "Staff", "en": "In front of the main entrance.", "ko": "정문 앞에서요."},
        ],
        "key_phrases": [
            {"en": "I'd like to book ___.", "ko": "___을 예약하고 싶어요"},
            {"en": "For how many people?", "ko": "몇 분이세요?"},
            {"en": "Where do we meet?", "ko": "어디서 모여요?"},
            {"en": "in front of ___", "ko": "___ 앞에서"},
        ],
        "tip": "예약은 'book'! 'book a tour / a table / a room' 다 됩니다.",
    },
    {
        "emoji": "😟",
        "title_en": "Making a Complaint",
        "title_ko": "정중하게 항의하기",
        "dialogue": [
            {"speaker": "You", "en": "Excuse me, this isn't what I ordered.", "ko": "실례합니다, 이건 제가 주문한 게 아니에요."},
            {"speaker": "Server", "en": "Oh, I'm so sorry. Let me fix that.", "ko": "아, 정말 죄송합니다. 바꿔 드릴게요."},
            {"speaker": "You", "en": "Also, my room is a bit noisy.", "ko": "그리고 제 방이 좀 시끄러워요."},
            {"speaker": "Clerk", "en": "I apologize. We can move you to another room.", "ko": "죄송합니다. 다른 방으로 옮겨 드릴 수 있어요."},
            {"speaker": "You", "en": "That would be great, thank you.", "ko": "그럼 좋겠네요, 감사합니다."},
        ],
        "key_phrases": [
            {"en": "This isn't what I ordered.", "ko": "이건 제가 주문한 게 아니에요"},
            {"en": "a bit noisy", "ko": "조금 시끄러운"},
            {"en": "That would be great.", "ko": "그럼 좋겠어요 (제안 수락)"},
            {"en": "Let me fix that.", "ko": "바로잡아 드릴게요"},
        ],
        "tip": "불만도 'Excuse me'로 부드럽게 시작하면 훨씬 정중하게 들려요.",
    },
    {
        "emoji": "🙏",
        "title_en": "Thanks & Goodbye",
        "title_ko": "감사 & 작별 인사",
        "dialogue": [
            {"speaker": "You", "en": "Thank you for everything. We had a great time.", "ko": "여러모로 감사했어요. 정말 즐거웠어요."},
            {"speaker": "Host", "en": "I'm so glad to hear that.", "ko": "그렇게 들으니 정말 기뻐요."},
            {"speaker": "You", "en": "I hope to come back someday.", "ko": "언젠가 다시 오고 싶어요."},
            {"speaker": "Host", "en": "You're always welcome. Take care!", "ko": "언제든 환영이에요. 조심히 가세요!"},
            {"speaker": "You", "en": "Take care. Goodbye!", "ko": "건강하세요. 안녕히 계세요!"},
        ],
        "key_phrases": [
            {"en": "Thank you for everything.", "ko": "여러모로 감사해요"},
            {"en": "We had a great time.", "ko": "정말 즐거웠어요"},
            {"en": "I hope to come back someday.", "ko": "언젠가 다시 오고 싶어요"},
            {"en": "Take care!", "ko": "잘 지내요 / 조심히 가요"},
        ],
        "tip": "헤어질 때 'Take care!'는 'Goodbye'보다 따뜻하고 자연스러워요.",
    },
]
